"""Merge handles and hashtags from allmysportsteamssuck.com into twitter_handles.csv.

- Fills proposed_hashtag for rows that are blank.
- Fills proposed_handle (+ sets verified=yes, confidence=medium) for rows with no handle yet
  (typically newly exported P4 teams). Never overwrites an existing handle.

Safe to re-run — only touches blank fields.
"""

import csv
import re
from pathlib import Path

SCRAPED = {
    ("Abilene Christian","football"):"ACU",("Abilene Christian","basketball"):"ACU",
    ("Air Force","football"):"AFFalcons",("Air Force","basketball"):"AFFalcons",
    ("Akron","football"):"GoZips",("Akron","basketball"):"GoZips",
    ("Alabama A&M","football"):"AAMU",("Alabama A&M","basketball"):"AAMU",
    ("Alabama State","football"):"myASU",("Alabama State","basketball"):"myASU",
    ("Albany","football"):"GreatDanes",("Albany","basketball"):"GreatDanes",
    ("Alcorn State","football"):"AlcornState",("Alcorn State","basketball"):"AlcornState",
    ("American","basketball"):"AmericanUni",
    ("App State","football"):"AppState",("App State","basketball"):"AppState",
    ("Appalachian State","football"):"AppState",("Appalachian State","basketball"):"AppState",
    ("Arkansas State","football"):"RedWolves",("Arkansas State","basketball"):"RedWolves",
    ("Arkansas-Pine Bluff","football"):"UAPB",("Arkansas-Pine Bluff","basketball"):"UAPB",
    ("Army","football"):"GoArmy",("Army","basketball"):"GoArmy",
    ("Austin Peay","football"):"AustinPeay",("Austin Peay","basketball"):"AustinPeay",
    ("Ball State","football"):"BallState",("Ball State","basketball"):"BallState",
    ("Baylor","football"):"Baylor",("Baylor","basketball"):"Baylor",
    ("Bellarmine","basketball"):"Bellarmine",
    ("Belmont","basketball"):"Belmont",
    ("Bethune-Cookman","football"):"BCU",("Bethune-Cookman","basketball"):"BCU",
    ("Binghamton","basketball"):"Binghamton",
    ("Boise State","football"):"BoiseState",("Boise State","basketball"):"BoiseState",
    ("Boston University","basketball"):"GoBU",
    ("Bowling Green","football"):"BowlingGreen",("Bowling Green","basketball"):"BowlingGreen",
    ("Bradley","basketball"):"Bradley",
    ("Brown","basketball"):"Brown",
    ("Bryant","football"):"Bryant",("Bryant","basketball"):"Bryant",
    ("Bucknell","football"):"Bucknell",("Bucknell","basketball"):"Bucknell",
    ("Buffalo","football"):"UBHornsUp",("Buffalo","basketball"):"UBHornsUp",
    ("Butler","football"):"Butler",("Butler","basketball"):"Butler",
    ("Cal Poly","football"):"CalPoly",("Cal Poly","basketball"):"CalPoly",
    ("Cal State-Bakersfield","basketball"):"CSUB",
    ("Cal State-Fullerton","basketball"):"CalStateFullerton",
    ("Cal State-Northridge","basketball"):"CSUN",
    ("California Baptist","basketball"):"CalBaptist",
    ("Campbell","football"):"Campbell",("Campbell","basketball"):"Campbell",
    ("Canisius","basketball"):"Canisius",
    ("Central Arkansas","football"):"CentralArkansas",("Central Arkansas","basketball"):"CentralArkansas",
    ("Central Connecticut State","football"):"CCSU",("Central Connecticut State","basketball"):"CCSU",
    ("Central Michigan","football"):"CentralMichigan",("Central Michigan","basketball"):"CentralMichigan",
    ("Charleston","basketball"):"CofC",
    ("Charleston Southern","football"):"CSUBucs",("Charleston Southern","basketball"):"CSUBucs",
    ("Charlotte","football"):"Charlotte",("Charlotte","basketball"):"Charlotte",
    ("Chattanooga","football"):"GoMocs",("Chattanooga","basketball"):"GoMocs",
    ("Chicago State","basketball"):"ChicagoState",
    ("Cleveland State","basketball"):"ClevelandState",
    ("Coastal Carolina","football"):"CCU",("Coastal Carolina","basketball"):"CCU",
    ("Colgate","football"):"Colgate",("Colgate","basketball"):"Colgate",
    ("Colorado State","football"):"CSURams",("Colorado State","basketball"):"CSURams",
    ("Columbia","football"):"Columbia",("Columbia","basketball"):"Columbia",
    ("Coppin State","basketball"):"CoppinState",
    ("Cornell","football"):"Cornell",("Cornell","basketball"):"Cornell",
    ("Creighton","basketball"):"Creighton",
    ("Dartmouth","football"):"Dartmouth",("Dartmouth","basketball"):"Dartmouth",
    ("Davidson","football"):"Davidson",("Davidson","basketball"):"Davidson",
    ("Dayton","football"):"GoFlyers",("Dayton","basketball"):"GoFlyers",
    ("Delaware","football"):"BlueHens",("Delaware","basketball"):"BlueHens",
    ("Delaware State","football"):"DelState",("Delaware State","basketball"):"DelState",
    ("Denver","basketball"):"DenverU",
    ("DePaul","basketball"):"DePaul",
    ("Detroit","basketball"):"DetroitU",
    ("Drake","football"):"Drake",("Drake","basketball"):"Drake",
    ("Drexel","basketball"):"Drexel",
    ("Duquesne","football"):"Duquesne",("Duquesne","basketball"):"Duquesne",
    ("East Carolina","football"):"ECU",("East Carolina","basketball"):"ECU",
    ("East Tennessee State","football"):"ETSU",("East Tennessee State","basketball"):"ETSU",
    ("Eastern Illinois","football"):"EIU",("Eastern Illinois","basketball"):"EIU",
    ("Eastern Kentucky","football"):"EKU",("Eastern Kentucky","basketball"):"EKU",
    ("Eastern Michigan","football"):"EMU",("Eastern Michigan","basketball"):"EMU",
    ("Eastern Washington","football"):"EWU",("Eastern Washington","basketball"):"EWU",
    ("Elon","football"):"Elon",("Elon","basketball"):"Elon",
    ("Evansville","basketball"):"Evansville",
    ("Fairfield","basketball"):"Fairfield",
    ("Fairleigh Dickinson","football"):"FDU",("Fairleigh Dickinson","basketball"):"FDU",
    ("Florida A&M","football"):"FAMU",("Florida A&M","basketball"):"FAMU",
    ("Florida Atlantic","football"):"FAU",("Florida Atlantic","basketball"):"FAU",
    ("Florida Gulf Coast","basketball"):"FGCU",
    ("Florida International","football"):"FIU",("Florida International","basketball"):"FIU",
    ("Fordham","football"):"Fordham",("Fordham","basketball"):"Fordham",
    ("Fresno State","football"):"FresnoState",("Fresno State","basketball"):"FresnoState",
    ("Furman","football"):"Furman",("Furman","basketball"):"Furman",
    ("Gardner-Webb","football"):"GardnerWebb",("Gardner-Webb","basketball"):"GardnerWebb",
    ("George Mason","basketball"):"GeorgeMason",
    ("George Washington","basketball"):"GWU",
    ("Georgetown","football"):"Georgetown",("Georgetown","basketball"):"Georgetown",
    ("Georgia Southern","football"):"GeorgiaSouthern",("Georgia Southern","basketball"):"GeorgiaSouthern",
    ("Georgia State","football"):"GeorgiaState",("Georgia State","basketball"):"GeorgiaState",
    ("Gonzaga","basketball"):"Zags",
    ("Grambling","football"):"Grambling",("Grambling","basketball"):"Grambling",
    ("Grand Canyon","basketball"):"GCU",
    ("Green Bay","basketball"):"GBPhoenix",
    ("Hampton","football"):"Hampton",("Hampton","basketball"):"Hampton",
    ("Harvard","football"):"Harvard",("Harvard","basketball"):"Harvard",
    ("Hawaii","football"):"HawaiiFB",("Hawaii","basketball"):"HawaiiMBB",
    ("High Point","basketball"):"HighPoint",
    ("Hofstra","basketball"):"Hofstra",
    ("Holy Cross","football"):"HolyCross",("Holy Cross","basketball"):"HolyCross",
    ("Houston Baptist","football"):"HoustonBaptist",("Houston Baptist","basketball"):"HoustonBaptist",
    ("Houston Christian","football"):"HoustonBaptist",("Houston Christian","basketball"):"HoustonBaptist",
    ("Howard","football"):"Howard",("Howard","basketball"):"Howard",
    ("Idaho","football"):"Vandals",("Idaho","basketball"):"Vandals",
    ("Idaho State","football"):"IdahoState",("Idaho State","basketball"):"IdahoState",
    ("Illinois State","football"):"IllinoisState",("Illinois State","basketball"):"IllinoisState",
    ("Illinois-Chicago","basketball"):"UIC",
    ("Incarnate Word","football"):"UIW",("Incarnate Word","basketball"):"UIW",
    ("Indiana State","football"):"IndianaState",("Indiana State","basketball"):"IndianaState",
    ("Iona","basketball"):"Iona",
    ("Jackson State","football"):"JacksonState",("Jackson State","basketball"):"JacksonState",
    ("Jacksonville","football"):"JUDolphins",("Jacksonville","basketball"):"JUDolphins",
    ("Jacksonville State","football"):"JSUGamecocks",("Jacksonville State","basketball"):"JSUGamecocks",
    ("James Madison","football"):"JMU",("James Madison","basketball"):"JMU",
    ("Kansas City","basketball"):"UMKC",
    ("Kennesaw State","football"):"KennesawState",("Kennesaw State","basketball"):"KennesawState",
    ("Kent State","football"):"KentState",("Kent State","basketball"):"KentState",
    ("La Salle","basketball"):"LaSalle",
    ("Lafayette","football"):"LafayetteLeopards",("Lafayette","basketball"):"LafayetteLeopards",
    ("Lamar","football"):"Lamar",("Lamar","basketball"):"Lamar",
    ("Lehigh","football"):"Lehigh",("Lehigh","basketball"):"Lehigh",
    ("Liberty","football"):"GoFlames",("Liberty","basketball"):"GoFlames",
    ("Lipscomb","basketball"):"Lipscomb",
    ("Little Rock","basketball"):"UALR",
    ("Long Beach State","basketball"):"LBSU",
    ("Long Island","football"):"LIUFB",("Long Island","basketball"):"LIUBB",
    ("Longwood","basketball"):"Longwood",
    ("Louisiana","football"):"RaginCajuns",("Louisiana","basketball"):"RaginCajuns",
    ("Louisiana Tech","football"):"LATech",("Louisiana Tech","basketball"):"LATech",
    ("Louisiana-Monroe","football"):"Warhawks",("Louisiana-Monroe","basketball"):"Warhawks",
    ("Loyola Marymount","basketball"):"LMU",
    ("Loyola-Chicago","basketball"):"LoyolaChicago",
    ("Loyola-Maryland","basketball"):"GoHounds",
    ("Loyola Maryland","basketball"):"GoHounds",
    ("Maine","football"):"BlackBears",("Maine","basketball"):"BlackBears",
    ("Manhattan","basketball"):"Jaspers",
    ("Marist","football"):"Marist",("Marist","basketball"):"Marist",
    ("Marshall","football"):"HerdNation",("Marshall","basketball"):"HerdNation",
    ("Maryland-Eastern Shore","football"):"UMES",("Maryland-Eastern Shore","basketball"):"UMES",
    ("Massachusetts","football"):"UMass",("Massachusetts","basketball"):"UMass",
    ("McNeese State","football"):"McNeese",("McNeese State","basketball"):"McNeese",
    ("McNeese","football"):"McNeese",("McNeese","basketball"):"McNeese",
    ("Memphis","football"):"GoTigersGo",("Memphis","basketball"):"GoTigersGo",
    ("Mercer","football"):"Mercer",("Mercer","basketball"):"Mercer",
    ("Merrimack","football"):"GoMack",("Merrimack","basketball"):"GoMack",
    ("Miami (OH)","football"):"Redhawks",("Miami (OH)","basketball"):"Redhawks",
    ("Middle Tennessee","football"):"MTSU",("Middle Tennessee","basketball"):"MTSU",
    ("Milwaukee","football"):"MilwaukeePanthers",("Milwaukee","basketball"):"MilwaukeePanthers",
    ("Mississippi Valley State","football"):"MVSU",("Mississippi Valley State","basketball"):"MVSU",
    ("Missouri State","football"):"MSUBears",("Missouri State","basketball"):"MSUBears",
    ("Monmouth","football"):"Monmouth",("Monmouth","basketball"):"Monmouth",
    ("Montana","football"):"GoGriz",("Montana","basketball"):"GrizHoops",
    ("Montana State","football"):"MSUBobcats",("Montana State","basketball"):"MSUBobcats",
    ("Morehead State","football"):"MSUEagles",("Morehead State","basketball"):"MSUEagles",
    ("Morgan State","football"):"MorganState",("Morgan State","basketball"):"MorganState",
    ("Mount St Mary's","basketball"):"TheMount",
    ("Murray State","football"):"Racers",("Murray State","basketball"):"Racers",
    ("Navy","football"):"Navy",("Navy","basketball"):"Navy",
    ("Nebraska-Omaha","basketball"):"Omavs",
    ("Omaha","basketball"):"Omavs",
    ("Nevada","football"):"BattleBorn",("Nevada","basketball"):"BattleBorn",
    ("New Hampshire","football"):"UNH",("New Hampshire","basketball"):"UNH",
    ("New Mexico","football"):"Lobos",("New Mexico","basketball"):"Lobos",
    ("New Mexico State","football"):"NMSU",("New Mexico State","basketball"):"NMSU",
    ("New Orleans","basketball"):"Privateers",
    ("Niagara","basketball"):"Niagara",
    ("Nicholls State","football"):"GeauxColonels",("Nicholls State","basketball"):"GeauxColonels",
    ("Nicholls","football"):"GeauxColonels",("Nicholls","basketball"):"GeauxColonels",
    ("NJIT","basketball"):"NJIT",
    ("Norfolk State","football"):"NSU",("Norfolk State","basketball"):"NSU",
    ("North Alabama","football"):"UNA",("North Alabama","basketball"):"UNA",
    ("North Carolina A&T","football"):"NCAT",("North Carolina A&T","basketball"):"NCAT",
    ("North Carolina Central","football"):"NCCU",("North Carolina Central","basketball"):"NCCU",
    ("North Dakota","football"):"UND",("North Dakota","basketball"):"UND",
    ("North Dakota State","football"):"NDSU",("North Dakota State","basketball"):"NDSU",
    ("North Florida","basketball"):"UNF",
    ("North Texas","football"):"MeanGreen",("North Texas","basketball"):"MeanGreen",
    ("Northeastern","basketball"):"Northeastern",
    ("Northern Arizona","football"):"NAU",("Northern Arizona","basketball"):"NAU",
    ("Northern Colorado","football"):"UNCBears",("Northern Colorado","basketball"):"UNCBears",
    ("Northern Illinois","football"):"NIU",("Northern Illinois","basketball"):"NIU",
    ("Northern Iowa","football"):"UNI",("Northern Iowa","basketball"):"UNI",
    ("Northern Kentucky","basketball"):"NKU",
    ("Northwestern State","football"):"NorthwesternState",("Northwestern State","basketball"):"NorthwesternState",
    ("Notre Dame","football"):"NotreDame",("Notre Dame","basketball"):"NotreDame",
    ("Oakland","basketball"):"OaklandMBB",
    ("Ohio","football"):"OhioBobcats",("Ohio","basketball"):"OhioBobcats",
    ("Old Dominion","football"):"ODU",("Old Dominion","basketball"):"ODU",
    ("Oral Roberts","basketball"):"ORU",
    ("Oregon State","football"):"GoBeavs",("Oregon State","basketball"):"GoBeavs",
    ("Pacific","basketball"):"Pacific",
    ("Penn","football"):"Penn",("Penn","basketball"):"Penn",
    ("Pepperdine","basketball"):"Pepperdine",
    ("Portland","basketball"):"GoPilots",
    ("Portland State","football"):"GoViks",("Portland State","basketball"):"GoViks",
    ("Prairie View A&M","football"):"PVAMU",("Prairie View A&M","basketball"):"PVAMU",
    ("Presbyterian","football"):"Presbyterian",("Presbyterian","basketball"):"Presbyterian",
    ("Princeton","football"):"Princeton",("Princeton","basketball"):"Princeton",
    ("Providence","basketball"):"PCBB",
    ("Purdue Fort Wayne","basketball"):"Mastodons",
    ("Quinnipiac","basketball"):"Quinnipiac",
    ("Radford","basketball"):"Radford",
    ("Rhode Island","football"):"URI",("Rhode Island","basketball"):"URI",
    ("Rice","football"):"Rice",("Rice","basketball"):"Rice",
    ("Richmond","football"):"Spiders",("Richmond","basketball"):"Spiders",
    ("Rider","basketball"):"Rider",
    ("Robert Morris","football"):"RMU",("Robert Morris","basketball"):"RMU",
    ("Sacramento State","football"):"SacState",("Sacramento State","basketball"):"SacState",
    ("Sacred Heart","football"):"SacredHeart",("Sacred Heart","basketball"):"SacredHeart",
    ("Saint Joseph's","basketball"):"StJoes",
    ("Saint Louis","basketball"):"Billikens",
    ("Saint Mary's","basketball"):"Gaels",
    ("Saint Peter's","basketball"):"Peacocks",
    ("Sam Houston State","football"):"Bearkats",("Sam Houston State","basketball"):"Bearkats",
    ("Sam Houston","football"):"Bearkats",("Sam Houston","basketball"):"Bearkats",
    ("Samford","football"):"Samford",("Samford","basketball"):"Samford",
    ("San Diego","football"):"USD",("San Diego","basketball"):"USD",
    ("San Diego State","football"):"Aztecs",("San Diego State","basketball"):"Aztecs",
    ("San Francisco","basketball"):"USFDons",
    ("San Jose State","football"):"SJSU",("San Jose State","basketball"):"SJSU",
    ("Santa Clara","basketball"):"SantaClara",
    ("Seattle","basketball"):"SeattleU",
    ("Seton Hall","basketball"):"SetonHall",
    ("Siena","basketball"):"Siena",
    ("SIU Edwardsville","basketball"):"SIUE",
    ("South Alabama","football"):"SouthAlabama",("South Alabama","basketball"):"SouthAlabama",
    ("South Carolina State","football"):"SCState",("South Carolina State","basketball"):"SCState",
    ("South Carolina Upstate","basketball"):"USCUpstate",
    ("South Dakota","football"):"SDCoyotes",("South Dakota","basketball"):"SDCoyotes",
    ("South Dakota State","football"):"GoJacks",("South Dakota State","basketball"):"GoJacks",
    ("South Florida","football"):"USF",("South Florida","basketball"):"USF",
    ("Southeast Missouri State","football"):"SeMO",("Southeast Missouri State","basketball"):"SeMO",
    ("Southeastern Louisiana","football"):"LionUp",("Southeastern Louisiana","basketball"):"LionUp",
    ("SE Louisiana","football"):"LionUp",("SE Louisiana","basketball"):"LionUp",
    ("Southern","football"):"SouthernU",("Southern","basketball"):"SouthernU",
    ("Southern Illinois","football"):"SIU",("Southern Illinois","basketball"):"SIU",
    ("Southern Miss","football"):"SouthernMiss",("Southern Miss","basketball"):"SouthernMiss",
    ("Southern Utah","football"):"SUU",("Southern Utah","basketball"):"SUU",
    ("St. Bonaventure","basketball"):"Bonnies",
    ("St. Francis","football"):"SFU",("St. Francis","basketball"):"SFU",
    ("St. John's","basketball"):"SJUBB",
    ("Stephen F. Austin","football"):"SFA",("Stephen F. Austin","basketball"):"SFA",
    ("Stetson","football"):"Stetson",("Stetson","basketball"):"Stetson",
    ("Stony Brook","football"):"StonyBrook",("Stony Brook","basketball"):"StonyBrook",
    ("Tarleton State","football"):"TexanNation",("Tarleton State","basketball"):"TexanNation",
    ("Tarleton","football"):"TexanNation",("Tarleton","basketball"):"TexanNation",
    ("Temple","football"):"Temple",("Temple","basketball"):"Temple",
    ("Tennessee State","football"):"TSUTigers",("Tennessee State","basketball"):"TSUTigers",
    ("Tennessee Tech","football"):"TNTech",("Tennessee Tech","basketball"):"TNTech",
    ("Tennessee-Martin","football"):"UTMartin",("Tennessee-Martin","basketball"):"UTMartin",
    ("UT Martin","football"):"UTMartin",("UT Martin","basketball"):"UTMartin",
    ("Texas A&M-Corpus Christi","basketball"):"TAMUCC",
    ("Texas Southern","football"):"TexasSouthern",("Texas Southern","basketball"):"TexasSouthern",
    ("Texas State","football"):"TexasState",("Texas State","basketball"):"TexasState",
    ("Texas-Arlington","basketball"):"UTA",
    ("UT Arlington","basketball"):"UTA",
    ("The Citadel","football"):"Citadel",("The Citadel","basketball"):"Citadel",
    ("Toledo","football"):"GoRockets",("Toledo","basketball"):"GoRockets",
    ("Towson","football"):"Towson",("Towson","basketball"):"Towson",
    ("Troy","football"):"Troy",("Troy","basketball"):"Troy",
    ("Tulane","football"):"RollWave",("Tulane","basketball"):"RollWave",
    ("Tulsa","football"):"TulsaFB",("Tulsa","basketball"):"TulsaHoops",
    ("UAB","football"):"UAB",("UAB","basketball"):"UAB",
    ("UC Davis","basketball"):"UCDavis",("UC-Davis","basketball"):"UCDavis",
    ("UC Irvine","basketball"):"UCIrvine",("UC-Irvine","basketball"):"UCIrvine",
    ("UC Riverside","basketball"):"UCRiverside",("UC-Riverside","basketball"):"UCRiverside",
    ("UC San Diego","basketball"):"UCSD",("UC-San Diego","basketball"):"UCSD",
    ("UC Santa Barbara","basketball"):"UCSB",("UC-Santa Barbara","basketball"):"UCSB",
    ("UMass Lowell","basketball"):"RiverHawks",("UMass-Lowell","basketball"):"RiverHawks",
    ("UMBC","basketball"):"UMBC",
    ("UNC Asheville","basketball"):"UNCAsheville",("UNC-Asheville","basketball"):"UNCAsheville",
    ("UNC Greensboro","basketball"):"UNCG",("UNC-Greensboro","basketball"):"UNCG",
    ("UNC Wilmington","basketball"):"UNCW",("UNC-Wilmington","basketball"):"UNCW",
    ("UNLV","football"):"UNLV",("UNLV","basketball"):"UNLV",
    ("Utah State","football"):"UtahState",("Utah State","basketball"):"UtahState",
    ("Utah Valley","basketball"):"UVU",
    ("UTEP","football"):"MinerStrong",("UTEP","basketball"):"MinerStrong",
    ("UTRGV","basketball"):"UTRGV",
    ("UT Rio Grande Valley","basketball"):"UTRGV",
    ("UTSA","football"):"UTSA",("UTSA","basketball"):"UTSA",
    ("Valparaiso","football"):"Valpo",("Valparaiso","basketball"):"Valpo",
    ("Vermont","basketball"):"UVM",
    ("Villanova","football"):"Nova",("Villanova","basketball"):"Nova",
    ("Virginia Commonwealth","basketball"):"VCU",
    ("Virginia Military","football"):"VMI",("Virginia Military","basketball"):"VMI",
    ("VMI","football"):"VMI",("VMI","basketball"):"VMI",
    ("Wagner","football"):"Wagner",("Wagner","basketball"):"Wagner",
    ("Washington State","football"):"GoCougs",("Washington State","basketball"):"GoCougs",
    ("Weber State","football"):"WeberState",("Weber State","basketball"):"WeberState",
    ("Western Carolina","football"):"WCU",("Western Carolina","basketball"):"WCU",
    ("Western Illinois","football"):"WIU",("Western Illinois","basketball"):"WIU",
    ("Western Kentucky","football"):"WKU",("Western Kentucky","basketball"):"WKU",
    ("Western Michigan","football"):"WMU",("Western Michigan","basketball"):"WMU",
    ("Wichita State","basketball"):"Shockers",
    ("William & Mary","football"):"GoTribe",("William & Mary","basketball"):"GoTribe",
    ("Winthrop","basketball"):"Winthrop",
    ("Wofford","football"):"Wofford",("Wofford","basketball"):"Wofford",
    ("Wright State","football"):"WrightState",("Wright State","basketball"):"WrightState",
    ("Wyoming","football"):"GoWyo",("Wyoming","basketball"):"GoWyo",
    ("Xavier","basketball"):"Xavier",
    ("Yale","football"):"Yale",("Yale","basketball"):"Yale",
    ("Youngstown State","football"):"YSU",("Youngstown State","basketball"):"YSU",
    # Display-name aliases not in the scraped source
    ("UConn","football"):"UConn",("UConn","basketball"):"UConn",
    ("UAlbany","basketball"):"GreatDanes",
    ("VCU","basketball"):"VCU",
    ("UIC","basketball"):"UIC",
    ("UL Monroe","football"):"Warhawks",("UL Monroe","basketball"):"Warhawks",
    ("Central Connecticut","football"):"CCSU",("Central Connecticut","basketball"):"CCSU",
    ("Marquette","basketball"):"MUBB",
    ("Mount St Mary","basketball"):"TheMount",
    ("Saint Francis","basketball"):"SFU",
    ("IU Indianapolis","basketball"):"IUPUI",
    ("UT Rio Grande","basketball"):"UTRGV",
}


SCRAPED_HANDLES = {
    ("Abilene Christian","football"):"ACUFootball",("Abilene Christian","basketball"):"ACU_MBB",
    ("Air Force","football"):"AF_Football",("Air Force","basketball"):"AF_MBB",
    ("Akron","football"):"ZipsFB",("Akron","basketball"):"ZipsMBB",
    ("Alabama","football"):"AlabamaFTBL",("Alabama","basketball"):"AlabamaMBB",
    ("Alabama A&M","football"):"AAMUFB",("Alabama A&M","basketball"):"Bulldogs_Hoops",
    ("Alabama State","football"):"BamaStateFB",("Alabama State","basketball"):"BamaStateMBB",
    ("Albany","football"):"UAlbanyFootball",("Albany","basketball"):"UAlbanyMBB",
    ("Alcorn State","football"):"BravesSports",("Alcorn State","basketball"):"BravesSports",
    ("American","basketball"):"AU_Mbasketball",
    ("App State","football"):"AppState_FB",("App State","basketball"):"AppStateMBB",
    ("Appalachian State","football"):"AppState_FB",("Appalachian State","basketball"):"AppStateMBB",
    ("Arizona","football"):"ArizonaFBall",("Arizona","basketball"):"APlayersProgram",
    ("Arizona State","football"):"ASUFootball",("Arizona State","basketball"):"SunDevilHoops",
    ("Arkansas","football"):"RazorbackFB",("Arkansas","basketball"):"RazorbackMBB",
    ("Arkansas State","football"):"AStateFB",("Arkansas State","basketball"):"AStateMB",
    ("Arkansas-Pine Bluff","football"):"UAPBLionsRoar",("Arkansas-Pine Bluff","basketball"):"UAPBLionsRoar",
    ("Army","football"):"ArmyWP_Football",("Army","basketball"):"ArmyWP_MBB",
    ("Auburn","football"):"AuburnFootball",("Auburn","basketball"):"AuburnMBB",
    ("Austin Peay","football"):"AustinePeayFB",("Austin Peay","basketball"):"AustinPeayMBB",
    ("Ball State","football"):"BallStateFB",("Ball State","basketball"):"BallStateMBB",
    ("Baylor","football"):"BUFootball",("Baylor","basketball"):"BaylorMBB",
    ("Bellarmine","basketball"):"BUKnightsMBB",
    ("Belmont","basketball"):"BelmontMBB",
    ("Bethune-Cookman","football"):"BCUGridiron",("Bethune-Cookman","basketball"):"BCUHoops",
    ("Binghamton","basketball"):"BinghamtonMBB",
    ("Boise State","football"):"BroncoSportsFB",("Boise State","basketball"):"BroncoSportsMBB",
    ("Boston College","football"):"BCFootball",("Boston College","basketball"):"BCMBB",
    ("Boston University","basketball"):"TerrierMBB",
    ("Bowling Green","football"):"BG_Football",("Bowling Green","basketball"):"BGSUMHoops",
    ("Bradley","basketball"):"BradleyUMBB",
    ("Brown","basketball"):"BrownBasketball",
    ("Bryant","football"):"BryantUFootball",("Bryant","basketball"):"BryantHoops",
    ("Bucknell","football"):"Bucknell_FB",("Bucknell","basketball"):"Bucknell_MBB",
    ("Buffalo","football"):"UBFootball",("Buffalo","basketball"):"UBMensHoops",
    ("Butler","football"):"ButlerUFootball",("Butler","basketball"):"ButlerMBB",
    ("BYU","football"):"BYUFootball",("BYU","basketball"):"BYUBasketball",
    ("Cal Poly","football"):"CalPolyFootball",("Cal Poly","basketball"):"CalPolyMBB",
    ("Cal State-Bakersfield","basketball"):"CSUB_MBB",
    ("Cal State-Fullerton","basketball"):"FullertonMBB",
    ("Cal State-Northridge","basketball"):"CSUNMBB",
    ("California","football"):"CalFootball",("California","basketball"):"CalMBBall",
    ("California Baptist","basketball"):"CBUmbb",
    ("Campbell","football"):"GoCamelsFB",("Campbell","basketball"):"GoCamelsMBB",
    ("Canisius","basketball"):"Griffs_MBB",
    ("Central Arkansas","football"):"UCA_Football",("Central Arkansas","basketball"):"UCAMBB",
    ("Central Connecticut","football"):"CCSUFootball",("Central Connecticut","basketball"):"CCSU_MBB",
    ("Central Connecticut State","football"):"CCSUFootball",("Central Connecticut State","basketball"):"CCSU_MBB",
    ("Central Michigan","football"):"CMU_Football",("Central Michigan","basketball"):"CMUMensBBall",
    ("Charleston","basketball"):"CofCBasketball",
    ("Charleston Southern","football"):"CSUFB",("Charleston Southern","basketball"):"CSU_MBBall",
    ("Charlotte","football"):"CharlotteFTBL",("Charlotte","basketball"):"CharlotteMBB",
    ("Chattanooga","football"):"GoMocsFB",("Chattanooga","basketball"):"GoMocsMBB",
    ("Chicago State","basketball"):"ChicagoStateMBB",
    ("Cincinnati","football"):"GoBearcatsFB",("Cincinnati","basketball"):"GoBearcatsMBB",
    ("Clemson","football"):"ClemsonFB",("Clemson","basketball"):"ClemsonMBB",
    ("Cleveland State","basketball"):"CSU_Basketball",
    ("Coastal Carolina","football"):"CoastalFootball",("Coastal Carolina","basketball"):"CoastalMBB",
    ("Colgate","football"):"ColgateFB",("Colgate","basketball"):"ColgateMBB",
    ("Colorado","football"):"RunRalphieRun",("Colorado","basketball"):"CUBuffsMBB",
    ("Colorado State","football"):"CSUFootball",("Colorado State","basketball"):"CSUMBasketball",
    ("Columbia","football"):"ColumbiaLionsFB",("Columbia","basketball"):"CULionsMBB",
    ("Connecticut","football"):"UConnFootball",("Connecticut","basketball"):"UConnMBB",
    ("UConn","football"):"UConnFootball",("UConn","basketball"):"UConnMBB",
    ("Coppin State","basketball"):"CoppinMBB",
    ("Cornell","football"):"BigRed_Football",("Cornell","basketball"):"CUBigRedHoops",
    ("Creighton","basketball"):"BluejayMBB",
    ("Dartmouth","football"):"DartFootball",("Dartmouth","basketball"):"DartmouthMBK",
    ("Davidson","football"):"DavidsonFB",("Davidson","basketball"):"DavidsonMBB",
    ("Dayton","football"):"DaytonFootball",("Dayton","basketball"):"DaytonMBB",
    ("Delaware","football"):"DelawareFB",("Delaware","basketball"):"DelawareMBB",
    ("Delaware State","football"):"DelSt_Football",("Delaware State","basketball"):"DSUMBB",
    ("Denver","basketball"):"DU_Mhoops",
    ("DePaul","basketball"):"DePaulHoops",
    ("Detroit","basketball"):"DetroitMBB",
    ("Drake","football"):"DrakeBulldogsFB",("Drake","basketball"):"DrakeBulldogsMB",
    ("Drexel","basketball"):"DrexelMBB",
    ("Duke","football"):"DukeFootball",("Duke","basketball"):"DukeMBB",
    ("Duquesne","football"):"DuqFB",("Duquesne","basketball"):"DuqMBB",
    ("East Carolina","football"):"ECUPiratesFB",("East Carolina","basketball"):"ECUBasketball",
    ("East Tennessee State","football"):"ETSUFootball",("East Tennessee State","basketball"):"ETSU_MBB",
    ("Eastern Illinois","football"):"EIUPantherFB",("Eastern Illinois","basketball"):"EIUBasketball",
    ("Eastern Kentucky","football"):"EKUFootball",("Eastern Kentucky","basketball"):"EKUHoops",
    ("Eastern Michigan","football"):"EMUFB",("Eastern Michigan","basketball"):"EMUHoops",
    ("Eastern Washington","football"):"EWUFootball",("Eastern Washington","basketball"):"EWUMBB",
    ("Elon","football"):"ElonFootball",("Elon","basketball"):"ElonMBasketball",
    ("Evansville","basketball"):"UEAthletics_MBB",
    ("Fairfield","basketball"):"StagsMensBBall",
    ("Fairleigh Dickinson","football"):"FDUFootball",("Fairleigh Dickinson","basketball"):"FDU_MBB",
    ("Fairleigh-Dickinson","football"):"FDUFootball",("Fairleigh-Dickinson","basketball"):"FDU_MBB",
    ("Florida","football"):"GatorsFB",("Florida","basketball"):"GatorsMBK",
    ("Florida A&M","football"):"FAMUAthletics",("Florida A&M","basketball"):"FAMU_MBB",
    ("Florida Atlantic","football"):"FAU_Football",("Florida Atlantic","basketball"):"FAU_Hoops",
    ("Florida Gulf Coast","basketball"):"FGCU_MBB",
    ("Florida International","football"):"FIUFootball",("Florida International","basketball"):"FIUHoops",
    ("Florida State","football"):"FSUFootball",("Florida State","basketball"):"FSUHoops",
    ("Fordham","football"):"FordhamFootball",("Fordham","basketball"):"FordhamMBB",
    ("Fresno State","football"):"FresnoStateFB",("Fresno State","basketball"):"FresnoStateMBB",
    ("Furman","football"):"PaladinFootball",("Furman","basketball"):"FurmanHoops",
    ("Gardner-Webb","football"):"GWUFootball",("Gardner-Webb","basketball"):"GWU_MBK",
    ("George Mason","basketball"):"MasonMBB",
    ("George Washington","basketball"):"GW_MBB",
    ("Georgetown","football"):"HoyasFB",("Georgetown","basketball"):"GeorgetownHoops",
    ("Georgia","football"):"FootballUGA",("Georgia","basketball"):"UGABasketball",
    ("Georgia Southern","football"):"GSAthletics_FB",("Georgia Southern","basketball"):"GSAthletics_MBB",
    ("Georgia State","football"):"GeorgiaStateFB",("Georgia State","basketball"):"GeorgiaStateMBB",
    ("Georgia Tech","football"):"GeorgiaTechFB",("Georgia Tech","basketball"):"GTMBB",
    ("Gonzaga","basketball"):"ZagMBB",
    ("Grambling","football"):"GSU_Tigers",("Grambling","basketball"):"gsutigers_mbb",
    ("Grand Canyon","basketball"):"GCU_MBB",
    ("Green Bay","basketball"):"GBPhoenixMBB",
    ("Hampton","football"):"Hampton_FB",("Hampton","basketball"):"Hampton_MBB",
    ("Harvard","football"):"HarvardFootball",("Harvard","basketball"):"HarvardMBB",
    ("Hawaii","football"):"HawaiiFootball",("Hawaii","basketball"):"HawaiiMBB",
    ("High Point","basketball"):"HPUMBB",
    ("Hofstra","basketball"):"HofstraMBB",
    ("Holy Cross","football"):"HCrossFB",("Holy Cross","basketball"):"HCrossMBB",
    ("Houston","football"):"UHCougarFB",("Houston","basketball"):"UHCougarMBK",
    ("Houston Baptist","football"):"HBU_Football",("Houston Baptist","basketball"):"HCUHoops",
    ("Houston Christian","football"):"HBU_Football",("Houston Christian","basketball"):"HCUHoops",
    ("Howard","football"):"HUBisonFootball",("Howard","basketball"):"HUMensBB",
    ("Idaho","football"):"VandalFootball",("Idaho","basketball"):"VandalHoops",
    ("Idaho State","football"):"IdahoStateFB",("Idaho State","basketball"):"IdahoStateBBall",
    ("Illinois","football"):"IlliniFootball",("Illinois","basketball"):"IlliniMBB",
    ("Illinois State","football"):"RedbirdFB",("Illinois State","basketball"):"Redbird_MBB",
    ("Illinois-Chicago","basketball"):"UICFlamesMBB",
    ("Incarnate Word","football"):"UIWFootball",("Incarnate Word","basketball"):"UIWMBB",
    ("Indiana","football"):"IndianaFootball",("Indiana","basketball"):"IndianaMBB",
    ("Indiana State","football"):"IndianaStateFB",("Indiana State","basketball"):"IndStMBB",
    ("Iona","basketball"):"IonaGaelsMBB",
    ("Iowa","football"):"HawkeyeFootball",("Iowa","basketball"):"IowaHoops",
    ("Iowa State","football"):"CycloneFB",("Iowa State","basketball"):"CycloneMBB",
    ("IU Indianapolis","basketball"):"iuindy_mbb",
    ("Jackson State","football"):"GoJSUTigersFB",("Jackson State","basketball"):"GoJSUTigersMBB",
    ("Jacksonville","football"):"JAX_FB",("Jacksonville","basketball"):"JAX_MBB",
    ("Jacksonville State","football"):"JSUGamecocksFB",("Jacksonville State","basketball"):"JSU_MBB",
    ("James Madison","football"):"JMUFootball",("James Madison","basketball"):"JMUMBasketball",
    ("Kansas","football"):"KU_Football",("Kansas","basketball"):"KUHoops",
    ("Kansas City","basketball"):"KCRoosMBB",
    ("Kansas State","football"):"KStateFB",("Kansas State","basketball"):"KStateMBB",
    ("Kennesaw State","football"):"KennesawStFB",("Kennesaw State","basketball"):"KSUOwlsMBB",
    ("Kent State","football"):"KentStFootball",("Kent State","basketball"):"KentStMBB",
    ("Kentucky","football"):"UKFootball",("Kentucky","basketball"):"KentuckyMBB",
    ("La Salle","basketball"):"LaSalleMBB",
    ("Lafayette","football"):"LafColFootball",("Lafayette","basketball"):"LafayetteMBB",
    ("Lamar","football"):"LamarFootball",("Lamar","basketball"):"LamarMBB",
    ("Lehigh","football"):"LehighFootball",("Lehigh","basketball"):"LehighMBB",
    ("Liberty","football"):"LibertyFootball",("Liberty","basketball"):"LibertyMBB",
    ("Lipscomb","basketball"):"LipscombMBB",
    ("Little Rock","basketball"):"LittleRockMBB",
    ("Long Beach State","basketball"):"LBSUhoops",
    ("Long Island","football"):"LIUSharksFB",("Long Island","basketball"):"LIUBasketball",
    ("Longwood","basketball"):"LongwoodMBB",
    ("Louisiana","football"):"RaginCajunsFB",("Louisiana","basketball"):"RaginCajunsMBB",
    ("Louisiana Tech","football"):"LATechFB",("Louisiana Tech","basketball"):"LATechHoops",
    ("Louisiana-Monroe","football"):"ULM_FB",("Louisiana-Monroe","basketball"):"ULM_MBB",
    ("UL Monroe","football"):"ULM_FB",("UL Monroe","basketball"):"ULM_MBB",
    ("Louisville","football"):"UofLFootball",("Louisville","basketball"):"LouisvilleMBB",
    ("Loyola Marymount","basketball"):"LMULionsMBB",
    ("Loyola-Chicago","basketball"):"RamblersMBB",
    ("Loyola Chicago","basketball"):"RamblersMBB",
    ("Loyola-Maryland","basketball"):"LoyolaMBB",
    ("Loyola Maryland","basketball"):"LoyolaMBB",
    ("LSU","football"):"LSUFootball",("LSU","basketball"):"LSUBasketball",
    ("Maine","football"):"BlackBearsFB",("Maine","basketball"):"BlackBearsMBB",
    ("Manhattan","basketball"):"JaspersMBB",
    ("Marist","football"):"Marist_Football",("Marist","basketball"):"MaristMBB",
    ("Marquette","basketball"):"MarquetteMBB",
    ("Marshall","football"):"HerdFB",("Marshall","basketball"):"HerdMBB",
    ("Maryland","football"):"TerpsFootball",("Maryland","basketball"):"TerrapinHoops",
    ("Maryland-Eastern Shore","football"):"ESHawksSports",("Maryland-Eastern Shore","basketball"):"ESHawksHoops",
    ("Massachusetts","football"):"UMassFootball",("Massachusetts","basketball"):"UMassBasketball",
    ("McNeese State","football"):"McNeeseFootball",("McNeese State","basketball"):"McNeeseMBB",
    ("McNeese","football"):"McNeeseFootball",("McNeese","basketball"):"McNeeseMBB",
    ("Memphis","football"):"MemphisFB",("Memphis","basketball"):"Memphis_MBB",
    ("Mercer","football"):"MercerFootball",("Mercer","basketball"):"MercerMBB",
    ("Merrimack","football"):"MerrimackFB",("Merrimack","basketball"):"MerrimackMBB",
    ("Miami","football"):"CanesFootball",("Miami","basketball"):"CanesHoops",
    ("Miami (OH)","football"):"MiamiOHFootball",("Miami (OH)","basketball"):"MiamiOH_Bball",
    ("Michigan","football"):"UMichFootball",("Michigan","basketball"):"UMichBBall",
    ("Michigan State","football"):"MSU_Football",("Michigan State","basketball"):"MSU_Basketball",
    ("Middle Tennessee","football"):"MT_FB",("Middle Tennessee","basketball"):"MT_MBB",
    ("Milwaukee","football"):"UWMFootball",("Milwaukee","basketball"):"MKE_MBB",
    ("Minnesota","football"):"GopherFootball",("Minnesota","basketball"):"GopherMBB",
    ("Mississippi State","football"):"HailStateFB",("Mississippi State","basketball"):"HailStateMBK",
    ("Mississippi Valley State","football"):"MSValleyFB",("Mississippi Valley State","basketball"):"ValleyStateMBB",
    ("Missouri","football"):"MizzouFootball",("Missouri","basketball"):"MizzouHoops",
    ("Missouri State","football"):"MOStateFootball",("Missouri State","basketball"):"MSUBearsHoops",
    ("Monmouth","football"):"MUHawksFB",("Monmouth","basketball"):"MonmouthBBall",
    ("Montana","football"):"MontanaGrizFB",("Montana","basketball"):"MontanaGrizBB",
    ("Montana State","football"):"MSUBobcatsFB",("Montana State","basketball"):"MSUBobcatsMBB",
    ("Morehead State","football"):"MSUEaglesFB",("Morehead State","basketball"):"MSUEaglesMBB",
    ("Morgan State","football"):"MorganStateFB",("Morgan State","basketball"):"MorganStBears",
    ("Mount St Mary","basketball"):"MountHoops",
    ("Murray State","football"):"RacersFootball",("Murray State","basketball"):"RacersHoops",
    ("Navy","football"):"NavyFB",("Navy","basketball"):"NavyBasketball",
    ("Nebraska","football"):"HuskerFBNation",("Nebraska","basketball"):"HuskerHoops",
    ("Nebraska-Omaha","basketball"):"OmahaMBB",("Omaha","basketball"):"OmahaMBB",
    ("Nevada","football"):"NevadaFootball",("Nevada","basketball"):"NevadaHoops",
    ("New Hampshire","football"):"UNH_Football",("New Hampshire","basketball"):"UNHMBB",
    ("New Mexico","football"):"UNMLoboFB",("New Mexico","basketball"):"UNMLoboMBB",
    ("New Mexico State","football"):"NMStateFootball",("New Mexico State","basketball"):"NMStateMBB",
    ("New Orleans","basketball"):"PrivateersMBB",
    ("Niagara","basketball"):"NiagaraMBB",
    ("Nicholls State","football"):"Nicholls_FB",("Nicholls State","basketball"):"Nicholls_MBB",
    ("Nicholls","football"):"Nicholls_FB",("Nicholls","basketball"):"Nicholls_MBB",
    ("NJIT","basketball"):"NJITHoops",
    ("Norfolk State","football"):"NSU_FB",("Norfolk State","basketball"):"NSU_Bball",
    ("North Alabama","football"):"UNAFootball",("North Alabama","basketball"):"UNA_MBB",
    ("North Carolina","football"):"TarHeelFootball",("North Carolina","basketball"):"UNC_Basketball",
    ("North Carolina A&T","football"):"Football_NCAT",("North Carolina A&T","basketball"):"NCATBasketball",
    ("North Carolina Central","football"):"NCCU_Football",("North Carolina Central","basketball"):"NCCU_MBB",
    ("North Carolina State","football"):"PackFootball",("North Carolina State","basketball"):"PackMensBball",
    ("North Dakota","football"):"UNDFootball",("North Dakota","basketball"):"UNDMBasketball",
    ("North Dakota State","football"):"NDSUFootball",("North Dakota State","basketball"):"NDSUmbb",
    ("North Florida","basketball"):"OspreysMBB",
    ("North Texas","football"):"MeanGreenFB",("North Texas","basketball"):"MeanGreenMBB",
    ("Northeastern","basketball"):"GoNUmbasketball",
    ("Northern Arizona","football"):"NAU_Football",("Northern Arizona","basketball"):"NAUBasketball",
    ("Northern Colorado","football"):"UNCBearsFB",("Northern Colorado","basketball"):"UNC_Bears",
    ("Northern Illinois","football"):"NIU_Football",("Northern Illinois","basketball"):"GoHuskiesMBB",
    ("Northern Iowa","football"):"UNIFootball",("Northern Iowa","basketball"):"UNImbb",
    ("Northern Kentucky","basketball"):"NKUNorseMBB",
    ("Northwestern","football"):"NUFBFamily",("Northwestern","basketball"):"NUMensBball",
    ("Northwestern State","football"):"NSUDemonsFB",("Northwestern State","basketball"):"NSUDemonsMBB",
    ("Notre Dame","football"):"NDFootball",("Notre Dame","basketball"):"NDMBB",
    ("Oakland","basketball"):"OaklandMBB",
    ("Ohio","football"):"OhioFootball",("Ohio","basketball"):"OhioMBasketball",
    ("Ohio State","football"):"OhioStateFB",("Ohio State","basketball"):"OhioStateHoops",
    ("Oklahoma","football"):"OU_Football",("Oklahoma","basketball"):"OU_MBBall",
    ("Oklahoma State","football"):"CowboyFB",("Oklahoma State","basketball"):"OSUMBB",
    ("Old Dominion","football"):"ODUFootball",("Old Dominion","basketball"):"ODUMBB",
    ("Ole Miss","football"):"OleMissFB",("Ole Miss","basketball"):"OleMissMBB",
    ("Oral Roberts","basketball"):"ORUMBB",
    ("Oregon","football"):"OregonFootball",("Oregon","basketball"):"OregonMBB",
    ("Oregon State","football"):"BeaverFB",("Oregon State","basketball"):"BeaverMBB",
    ("Pacific","basketball"):"PacificMensBB",
    ("Penn","football"):"PennFB",("Penn","basketball"):"PennBasketball",
    ("Penn State","football"):"PennStateFball",("Penn State","basketball"):"PennStateMBB",
    ("Pepperdine","basketball"):"PeppBasketball",
    ("Pittsburgh","football"):"Pitt_FB",("Pittsburgh","basketball"):"Pitt_MBB",
    ("Portland","basketball"):"PilotHoops",
    ("Portland State","football"):"PSUViksFB",("Portland State","basketball"):"PSUViksMBB",
    ("Prairie View A&M","football"):"PVAMUFootball",("Prairie View A&M","basketball"):"PVAMUPanthers",
    ("Presbyterian","football"):"BlueHoseFtball",("Presbyterian","basketball"):"BlueHoseHoops",
    ("Princeton","football"):"PUTigerFootball",("Princeton","basketball"):"Princeton_Hoops",
    ("Providence","basketball"):"PCFriarsMBB",
    ("Purdue","football"):"BoilerFootball",("Purdue","basketball"):"BoilerBall",
    ("Purdue Fort Wayne","basketball"):"MastodonMBB",
    ("Quinnipiac","basketball"):"QU_MBB",
    ("Radford","basketball"):"RadfordMBB",
    ("Rhode Island","football"):"RhodyFootball",("Rhode Island","basketball"):"RhodyMBB",
    ("Rice","football"):"RiceFootball",("Rice","basketball"):"RiceBasketball",
    ("Richmond","football"):"SpiderFootball",("Richmond","basketball"):"SpiderMBB",
    ("Rider","basketball"):"RiderMBB",
    ("Robert Morris","football"):"RMUFootball",("Robert Morris","basketball"):"RMUMBasketball",
    ("Rutgers","football"):"Rfootball",("Rutgers","basketball"):"RutgersMBB",
    ("Sacramento State","football"):"SacHornetsFB",("Sacramento State","basketball"):"SacHornetsMBB",
    ("Sacred Heart","football"):"SHU__Football",("Sacred Heart","basketball"):"SHU_MensHoops",
    ("Saint Joseph's","basketball"):"SJUHawks_MBB",
    ("Saint Louis","basketball"):"SaintLouisMBB",
    ("Saint Mary's","basketball"):"SaintMarysHoops",
    ("Saint Peter's","basketball"):"PeacocksMBB",
    ("Sam Houston State","football"):"BearkatsFB",("Sam Houston State","basketball"):"BearkatsMBB",
    ("Sam Houston","football"):"BearkatsFB",("Sam Houston","basketball"):"BearkatsMBB",
    ("Samford","football"):"SamfordFootball",("Samford","basketball"):"SamfordMBB",
    ("San Diego","football"):"USDFootball",("San Diego","basketball"):"USDMBB",
    ("San Diego State","football"):"SDSUFootball",("San Diego State","basketball"):"Aztec_MBB",
    ("San Francisco","basketball"):"USFDonsMBB",
    ("San Jose State","football"):"SJSUSpartanFB",("San Jose State","basketball"):"SJSUMBB",
    ("Santa Clara","basketball"):"SantaClaraHoops",
    ("Seattle","basketball"):"SeattleUMBB",
    ("Seton Hall","basketball"):"SetonHallMBB",
    ("Siena","basketball"):"SienaMBB",
    ("SIU Edwardsville","basketball"):"SIUEMBB",
    ("SIU-Edwardsville","basketball"):"SIUEMBB",
    ("SMU","football"):"SMU_Football",("SMU","basketball"):"SMUBasketball",
    ("South Alabama","football"):"WeAreSouth_FB",("South Alabama","basketball"):"WeAreSouth_MBB",
    ("South Carolina","football"):"GamecockFB",("South Carolina","basketball"):"GamecockMBB",
    ("South Carolina State","football"):"SCState_FB",("South Carolina State","basketball"):"SCStateMBB",
    ("South Carolina Upstate","basketball"):"UpstateMB",
    ("South Dakota","football"):"SDCoyotesFB",("South Dakota","basketball"):"SDCoyotesMBB",
    ("South Dakota State","football"):"GoJacksFB",("South Dakota State","basketball"):"GoJacksMBB",
    ("South Florida","football"):"USFFootball",("South Florida","basketball"):"USFMBB",
    ("Southeast Missouri State","football"):"SEMOFootball",("Southeast Missouri State","basketball"):"SEMOMBB",
    ("Southeastern Louisiana","football"):"SLUFootball",("Southeastern Louisiana","basketball"):"SLU_Hoops",
    ("SE Louisiana","football"):"SLUFootball",("SE Louisiana","basketball"):"SLU_Hoops",
    ("Southern","football"):"SouthernUsports",("Southern","basketball"):"JaguarHoops",
    ("Southern Illinois","football"):"SIU_Football",("Southern Illinois","basketball"):"SIU_Basketball",
    ("Southern Miss","football"):"SouthernMissFB",("Southern Miss","basketball"):"SouthernMissMBB",
    ("Southern Utah","football"):"SUUFB",("Southern Utah","basketball"):"SUUBasketball",
    ("St. Bonaventure","basketball"):"BonniesMBB",
    ("St. Francis","football"):"RedFlashFB",("St. Francis","basketball"):"RedFlashMBB",
    ("Saint Francis","basketball"):"RedFlashMBB",
    ("St. John's","basketball"):"StJohnsBBall",
    ("Stanford","football"):"StanfordFball",("Stanford","basketball"):"StanfordMBB",
    ("Stephen F. Austin","football"):"SFA_Football",("Stephen F. Austin","basketball"):"SFA_MBB",
    ("Stetson","football"):"StetsonFootball",("Stetson","basketball"):"StetsonMBB",
    ("Stony Brook","football"):"StonyBrookFB",("Stony Brook","basketball"):"StonyBrookMBB",
    ("Syracuse","football"):"CuseFootball",("Syracuse","basketball"):"Cuse_MBB",
    ("Tarleton State","football"):"TarletonFB",("Tarleton State","basketball"):"TarletonMBB",
    ("Tarleton","football"):"TarletonFB",("Tarleton","basketball"):"TarletonMBB",
    ("TCU","football"):"TCUFootball",("TCU","basketball"):"TCUBasketball",
    ("Temple","football"):"Temple_FB",("Temple","basketball"):"TUMBBHoops",
    ("Tennessee","football"):"Vol_Football",("Tennessee","basketball"):"Vol_Hoops",
    ("Tennessee State","football"):"TSU_Football",("Tennessee State","basketball"):"TSUTigersMBB",
    ("Tennessee Tech","football"):"TNTechFootball",("Tennessee Tech","basketball"):"TTU_Basketball",
    ("Tennessee-Martin","football"):"UTM_Football",("Tennessee-Martin","basketball"):"SkyhawkHoops",
    ("UT Martin","football"):"UTM_Football",("UT Martin","basketball"):"SkyhawkHoops",
    ("Texas","football"):"TexasFootball",("Texas","basketball"):"TexasMBB",
    ("Texas A&M","football"):"AggieFootball",("Texas A&M","basketball"):"AggieMBK",
    ("Texas A&M-Corpus Christi","basketball"):"IslandersMBB",
    ("Texas Southern","football"):"TSUFootball",("Texas Southern","basketball"):"TSUMensHoops",
    ("Texas State","football"):"TXStateFootball",("Texas State","basketball"):"TXStateMBB",
    ("Texas Tech","football"):"TexasTechFB",("Texas Tech","basketball"):"TexasTechMBB",
    ("Texas-Arlington","basketball"):"UTA_MBB",
    ("UT Arlington","basketball"):"UTA_MBB",
    ("The Citadel","football"):"CitadelFootball",("The Citadel","basketball"):"CitadelHoops",
    ("Toledo","football"):"ToledoFB",("Toledo","basketball"):"ToledoMBB",
    ("Towson","football"):"Towson_FB",("Towson","basketball"):"Towson_MBB",
    ("Troy","football"):"TroyTrojansFB",("Troy","basketball"):"TroyTrojansMBB",
    ("Tulane","football"):"GreenWaveFB",("Tulane","basketball"):"GreenWaveMBB",
    ("Tulsa","football"):"TulsaFootball",("Tulsa","basketball"):"TUMBasketball",
    ("UAB","football"):"UAB_FB",("UAB","basketball"):"UAB_MBB",
    ("UCLA","football"):"UCLAFootball",("UCLA","basketball"):"UCLAMBB",
    ("UAlbany","basketball"):"UAlbanyMBB",
    ("UC Davis","basketball"):"UCDavisMBB",("UC-Davis","basketball"):"UCDavisMBB",
    ("UC Irvine","basketball"):"UCImbb",("UC-Irvine","basketball"):"UCImbb",
    ("UC Riverside","basketball"):"UCRMBB",("UC-Riverside","basketball"):"UCRMBB",
    ("UC San Diego","basketball"):"UCSDmbb",("UC-San Diego","basketball"):"UCSDmbb",
    ("UC Santa Barbara","basketball"):"UCSBbasketball",("UC-Santa Barbara","basketball"):"UCSBbasketball",
    ("UIC","basketball"):"UICFlamesMBB",
    ("UMass Lowell","basketball"):"RiverHawkMBB",("UMass-Lowell","basketball"):"RiverHawkMBB",
    ("UMBC","basketball"):"UMBC_MBB",
    ("UNC Asheville","basketball"):"UNCAvlMBB",("UNC-Asheville","basketball"):"UNCAvlMBB",
    ("UNC Greensboro","basketball"):"UNCGBasketball",("UNC-Greensboro","basketball"):"UNCGBasketball",
    ("UNC Wilmington","basketball"):"UNCWMensHoops",("UNC-Wilmington","basketball"):"UNCWMensHoops",
    ("UNLV","football"):"UNLVFootball",("UNLV","basketball"):"TheRunninRebels",
    ("USC","football"):"USC_FB",("USC","basketball"):"USC_Hoops",
    ("Utah","football"):"Utah_Football",("Utah","basketball"):"UtahMBB",
    ("Utah State","football"):"USUFootball",("Utah State","basketball"):"USUBasketball",
    ("Utah Valley","basketball"):"UVUMBB",
    ("UTEP","football"):"UTEPFB",("UTEP","basketball"):"UTEP_MBB",
    ("UTRGV","basketball"):"UTRGVMBB",
    ("UT Rio Grande Valley","basketball"):"UTRGVMBB",
    ("UTSA","football"):"UTSAFtbl",("UTSA","basketball"):"UTSAMBB",
    ("Valparaiso","football"):"ValpoUFootball",("Valparaiso","basketball"):"ValpoBasketball",
    ("Vanderbilt","football"):"VandyFootball",("Vanderbilt","basketball"):"VandyMBB",
    ("Vermont","basketball"):"UVMmbb",
    ("VCU","basketball"):"VCU_Hoops",
    ("Virginia Commonwealth","basketball"):"VCU_Hoops",
    ("Villanova","football"):"NovaFootball",("Villanova","basketball"):"NovaMBB",
    ("Virginia","football"):"UVAFootball",("Virginia","basketball"):"UVAMensHoops",
    ("Virginia Military","football"):"VMI_Football",("Virginia Military","basketball"):"VMI_Basketball",
    ("VMI","football"):"VMI_Football",("VMI","basketball"):"VMI_Basketball",
    ("Virginia Tech","football"):"VT_Football",("Virginia Tech","basketball"):"HokiesMBB",
    ("Wagner","football"):"Wagner_Football",("Wagner","basketball"):"Wagner_MBB",
    ("Wake Forest","football"):"WakeFB",("Wake Forest","basketball"):"WakeMBB",
    ("Washington","football"):"UW_Football",("Washington","basketball"):"UW_MBB",
    ("Washington State","football"):"WSUCougarFB",("Washington State","basketball"):"WSUMensHoops",
    ("Weber State","football"):"WeberStateFB",("Weber State","basketball"):"WeberStateMBB",
    ("West Virginia","football"):"WVUFootball",("West Virginia","basketball"):"WVUHoops",
    ("Western Carolina","football"):"WCU_FB",("Western Carolina","basketball"):"WCU_MBB",
    ("Western Illinois","football"):"WIUFootball",("Western Illinois","basketball"):"WIUMensHoops",
    ("Western Kentucky","football"):"WKUFootball",("Western Kentucky","basketball"):"WKUBasketball",
    ("Western Michigan","football"):"WMU_Football",("Western Michigan","basketball"):"WMUMBB",
    ("Wichita State","basketball"):"GoShockersMBB",
    ("William & Mary","football"):"WMTribeFootball",("William & Mary","basketball"):"WMTribeMBB",
    ("Winthrop","basketball"):"Winthrop_MBB",
    ("Wisconsin","football"):"BadgerFootball",("Wisconsin","basketball"):"BadgerMBB",
    ("Wofford","football"):"Wofford_FB",("Wofford","basketball"):"WoffordMBB",
    ("Wright State","football"):"WrightStFball",("Wright State","basketball"):"WSU_MBB",
    ("Wyoming","football"):"Wyo_Football",("Wyoming","basketball"):"Wyo_MBB",
    ("Xavier","basketball"):"XavierMBB",
    ("Yale","football"):"Yale_Football",("Yale","basketball"):"Yale_Basketball",
    ("Youngstown State","football"):"YoungstownStFB",("Youngstown State","basketball"):"YSUMensHoops",
}

SCRAPE_SOURCE = "https://www.allmysportsteamssuck.com/ncaa-division-i-football-and-basketball-twitter-hashtags-and-handles/"


def normalize(s):
    # Fold accented chars before stripping punctuation so é→e, ʻ→ etc.
    s = s.replace("é", "e").replace("É", "E").replace("ʻ", "").replace("'", "").replace("'", "")
    s = re.sub(r"[^a-z0-9 ]", " ", s.lower())
    return re.sub(r" +", " ", s).strip()


def _longest_prefix_match(lookup, display_name, sport):
    norm_display = normalize(display_name)
    best = ("", "")
    for (name, sp), val in lookup.items():
        if sp != sport:
            continue
        norm_name = normalize(name)
        if norm_display.startswith(norm_name) and len(norm_name) > len(best[0]):
            best = (norm_name, val)
    return best[1]


def find_handle(display_name, sport):
    if sport not in ("football", "basketball"):
        return ""
    return _longest_prefix_match(SCRAPED_HANDLES, display_name, sport)


def find_hashtag(display_name, sport):
    if sport not in ("football", "basketball"):
        return ""
    return _longest_prefix_match(SCRAPED, display_name, sport)


def main():
    csv_path = Path(__file__).parent / "data" / "twitter_handles.csv"
    rows = list(csv.DictReader(csv_path.open(encoding="utf-8-sig")))
    print(f"CSV rows: {len(rows)}")

    handles_filled = hashtags_filled = already_done = no_match = 0

    for row in rows:
        display = row["team_display_name"]
        sport = row["sport_key"]
        has_handle = bool(row.get("proposed_handle", "").strip())
        has_hashtag = bool(row.get("proposed_hashtag", "").strip())

        # Fill handle from scraped data only when blank (don't overwrite manual research)
        if not has_handle:
            handle = find_handle(display, sport)
            if handle:
                row["proposed_handle"] = handle
                row["verified"] = "yes"
                row["confidence"] = "medium"
                if not row.get("source_url", "").strip():
                    row["source_url"] = SCRAPE_SOURCE
                handles_filled += 1

        # Fill hashtag when blank
        if not has_hashtag:
            tag = find_hashtag(display, sport)
            if tag:
                row["proposed_hashtag"] = tag
                hashtags_filled += 1
            elif sport in ("football", "basketball") and not row.get("proposed_handle", "").strip():
                no_match += 1
        else:
            if has_handle:
                already_done += 1

    print(f"Handles filled: {handles_filled}, Hashtags filled: {hashtags_filled}, "
          f"Already complete: {already_done}, No match: {no_match}")

    fieldnames = list(rows[0].keys())
    if "proposed_hashtag" not in fieldnames:
        idx = fieldnames.index("proposed_handle") + 1
        fieldnames.insert(idx, "proposed_hashtag")

    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"Written: {csv_path}")


if __name__ == "__main__":
    main()
